version: "3.9"

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb_cluster_1
    restart: on-failure
    entrypoint:
      [
        "/usr/bin/mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all"
      ]
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    ports:
      - 30001:27017
    expose:
      - 27017
  mongodb2:
    image: mongo:latest
    container_name: mongodb_cluster_2
    restart: on-failure
    entrypoint:
      [
        "/usr/bin/mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all"
      ]
    ports:
      - 30002:27017
    expose:
      - 27017
    depends_on:
      - mongodb1
  mongodb3:
    image: mongo:latest
    container_name: mongodb_cluster_3
    restart: on-failure
    entrypoint:
      [
        "/usr/bin/mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all"
      ]
    ports:
      - 30003:27017
    expose:
      - 27017
    depends_on:
      - mongodb1
  mongodb_setup:
    image: mongo:latest
    container_name: "mongodb_setup"
    restart: on-failure
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    volumes:
      - ./deployment_scripts:/deployment_scripts
    entrypoint: [ "sh", "deployment_scripts/iniciate_replica.sh" ]
  rabbitmq:
    image: rabbitmq:latest
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
volumes:
  mongodata:
  mongoconfig:


networks:
  rabbitmq_go_net:
    driver: bridge
