/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/BookingService": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SubmitTravel"];
          "text/json": components["schemas"]["SubmitTravel"];
          "application/*+json": components["schemas"]["SubmitTravel"];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    SubmitTravel: {
      /** Format: uuid */
      userId?: string;
      from?: string | null;
      to?: string | null;
      /** Format: int32 */
      hotelId?: number;
      /** Format: date-time */
      departure?: string;
    };
  };
}

export interface operations {}

export interface external {}
